name: Build & Release (tag)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Gutenbergをバンドルする場合だけ有効化
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - run: npm run build --if-present

      - name: Create ZIP
        run: |
          PLUGIN=swipe-lp-lite
          zip -r ${PLUGIN}.zip . \
            -x ".git/*" ".github/*" "node_modules/*" ".wp-env/*" ".DS_Store" \
               "*.map" "package-lock.json" "yarn.lock" "pnpm-lock.yaml"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: swipe-lp-lite.zip
